
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';

const SET_USERS = 'SET_USERS';
const SET_USER_MESSAGES = 'SET_USER_MESSAGES';
const SET_SELECTED_USER = 'SET_SELECTED_USER';
const ADD_MESSAGE = 'ADD_MESSAGE';
const ADD_REACTION = 'ADD_REACTION';

export {
    LOGIN,
    LOGOUT,
    SET_USERS,
    SET_USER_MESSAGES,
    SET_SELECTED_USER,
    ADD_MESSAGE,
    ADD_REACTION
}